### PR TITLE
GTKmm rewrite

### LINKED ISSUE #40: Using gtkmm instead of plain gtk?
Devs, would you accept a PR with rewriting of the project to gtkmm? Tbh, plain C-style GTK code is pretty hard to read and change.

### PR DESCRIPTION
**Pull request by NamorNiradnug**
Implements #40
(Fixes #40)
Not ready yet

### CODE REVIEW

**Comment by NamorNiradnug** [comment]
It's mostly ready, maybe I'll change some minor stuff like margins (today or tomorrow). There is still debug printing, I'll remove it after review (in case any bugs will be found).

**Comment by soreau** [comment]
Hi, thanks for working on this! I see this cannot be merged because the branch has conflicts that must be resolved. I think if you rebase on current master, it might fix this. I have not tested this yet, but it looks quite promising. Also I wanted to ask if you intend to help maintaining the code going forward if we do merge this? Great work, thanks again.

**Comment by soreau** [comment]
I built and preliminary tested your code and I have to say, it looks very good on the first try. +1,887 −3,865 is amazing. It built fine and ran, but I wonder why the window is a different initial size than before. When I look with GTK_DEBUG=interactive, it seems the GtkFlowBoxChild is a lot larger in width than the GtkBox that is the button. So there's this seemingly dead space between the right of each button and the next plugin checkbox. Matching the size isn't a deal-breaker, but more of a curiosity. However I notice the screenshot isn't up-to-date, can you make another latest screenshot? The input grab for key/button bindings worked for me, great job there. Another thing I noticed in the Command plugin is that when you add a new command, it doesn't expand the newly created dropdown and highlight the <command> text. We could probably just focus the command field and don't write <command> there, but I think it should be expanded at least. And when I removed an entry and re-added it, the numbers became out of order when the command appeared at the bottom. Maybe it would be easier to not reveal the command numbers in wcm command interface? Some or all of these problems with command might be present in current wcm, and if any of them are, feel free to ignore. One last nitpick, can we use `#pragma once` in the headers instead of #ifndef/#define/#endif?

**Comment by NamorNiradnug** [comment]
> So there's this seemingly dead space between the right of each button and the next plugin checkbox.

The reason is that there is a plugin with a long name ("Extra Touchscreen gestures"), and all the buttons are the same size. Maybe we should `set_max_chars_width`.

**Comment by NamorNiradnug** [comment]
> And when I removed an entry and re-added it, the numbers became out of order when the command appeared at the bottom.

I think it is better to put newly added commands in the end of list without sorting, so that user could see it without scrolling the list. After reopening it becomes sorted.

**Comment by soreau** [comment]
> > So there's this seemingly dead space between the right of each button and the next plugin checkbox.
> 
> The reason is that there is a plugin with a long name ("Extra Touchscreen gestures"), and all the buttons are the same size. Maybe we should `set_max_chars_width`?

The long plugin name is not the reason, because it would affect current wcm the same way. I have taken the liberty of making screenshots to show you. This is the original:

file:///tmp/wcm-orig.png

and this is from the new code:

file:///tmp/wcm-new.png

As you can see, there is a dead space where there previously was none.

**Comment by NamorNiradnug** [comment]
> > > So there's this seemingly dead space between the right of each button and the next plugin checkbox.
> > 
> > 
> > The reason is that there is a plugin with a long name ("Extra Touchscreen gestures"), and all the buttons are the same size. Maybe we should `set_max_chars_width`?
> 
> The long plugin name is not the reason, because it would affect current wcm the same way. I have taken the liberty of making screenshots to show you. This is the original:
> 
> wcm-orig
> 
> and this is from the new code:
> 
> wcm-new
> 

> As you can see, there is a dead space where there previously was none.

Ah, I see. That's because FlowBox arranges and resizes its children so that they fill all the horizontal space. In the original there is a lot of empty space too, but only on the right, isn't it?

view_2023-01-15_16-47-11

Also the original shrinks long names sometimes, which is a good thing: 

view_2023-01-15_16-47-21

**Comment by soreau** [comment]
Here, the original looks like this:

wcm

**Comment by soreau** [comment]
Now that I look more closely, I see I can resize the width smaller, and it fixes the problem. So, I think we only need to size the main window, something like the original code does [here](https://github.com/WayfireWM/wcm/blob/master/src/main.cpp#L169).

**Comment by NamorNiradnug** [comment]
It looks like this with `window.set_default_size(1000, 580);`. 

view_2023-01-15_21-05-08

With `flowbox.set_min_children_per_line(3)` it looks like this:
view_2023-01-15_21-07-53

**Comment by NamorNiradnug** [comment]
Is the second

**Comment by NamorNiradnug** [comment]
I think it looks okay with `flowbox.set_min_children` and `window.set_default_size(1000, 580)`, doesn't it?

**Comment by soreau** [comment]
> I think it looks okay with `flowbox.set_min_children` and `window.set_default_size(1000, 580)`, doesn't it?

Yes, this looks better I think. Thanks for looking into this. I will keep running this for a few more days of testing and if I don't find any major technical issues, I think we should be good to merge.

**Comment by soreau** [comment]
By the way, can you possibly run the code through uncrustify using wayfire's uncrustify.ini and ammen99's patched uncrustify so we're on the same page? I have uncrustify run automatically as a git commit hook, for what it's worth. Also, you might as well add yourself to the LICENSE file while you're at it.

**Comment by soreau** [comment]
The only nitpick left that I have is that when maximized (or resize the width larger), the plugin button columns don't match across categories if there are say, three in one and more in another. Also I don't understand why your new screenshot has the same category icon for two categories. We can work on such cosmetic details later though.

Aside from that, LGTM, thanks for rewriting WCM!

**Pull request merged**
