### PR TITLE
Change icon "back" to draw-arrow-back"

### PR DESCRIPTION
**Pull request by NamorNiradnug**

### CODE REVIEW

**Comment by soreau** [comment]
There should be a good reason along with this change but I see none. Can you please explain why you think this would be a change for the better?

**Comment by NamorNiradnug** [comment]
> There should be a good reason along with this change but I see none. Can you please explain why you think this would be a change for the better?

There is no icon for "back" in icon themes such as Adwaita and Breeze, so i think that is not a standart icon. There is "draw-arrow-back" in Breeze (and Candy), so it works by default for users with the themes unlike "back". Probably not good enough reason.

**Comment by soreau** [comment]
I tried Adwaita and Breeze, light and dark, but in all cases, the icon exists and is loaded in wcm. Can you show a screenshot of the problem? To be clear, it's the icon in the Back button after clicking on any plugin. I am pretty sure "back" exists. Maybe your installation is faulty?

**Comment by NamorNiradnug** [comment]
That's the same when using only Adwaita icons not as a fallback
view_2022-06-07_22-33-49

**Comment by marcusbritanicus** [comment]
@soreau I do agree with @NamorNiradnug that the icon name should not be `back` since there is no standard icon named `back`.
However, I would prefer if the icon name was `go-previous`, this is a [standard icon name](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#names)

**Comment by soreau** [comment]
@marcusbritanicus Yes, 'go-previous' is in gtk3-icon-browser whereas 'back' and 'draw-arrow-back' are not.

@NamorNiradnug I will accept the change to 'go-previous'.

**Pull request merged**
