### PR TITLE
Refactor animation duration config UI

### PR DESCRIPTION
**Pull request by NamorNiradnug**
Related to #80

### CODE REVIEW

**Comment by NamorNiradnug** [comment]
Requires https://github.com/WayfireWM/wf-config/pull/71

**Comment by soreau** [comment]
The PR seems to work ok, but my only nitpick is cosmetic. I would like to retain the order of the combobox of easings as I had it: `linear`, `circle`, `sigmoid`, `easeOutElastic`. However I'd also like to fix the bug mentioned [here](https://github.com/WayfireWM/wcm/pull/80#issuecomment-2186220598), whether it's in another PR or this one.

**Comment by NamorNiradnug** [comment]
> The PR seems to work ok, but my only nitpick is cosmetic. I would like to retain the order of the combobox of easings as I had it: `linear`, `circle`, `sigmoid`, `easeOutElastic`. However I'd also like to fix the bug mentioned [here](https://github.com/WayfireWM/wcm/pull/80#issuecomment-2186220598), whether it's in another PR or this one.

I also noticed the bug back then and even tried to fix it but I didn't find out how. I'll look into that again and share my thoughts.

**Comment by NamorNiradnug** [comment]
> I would like to retain the order of the combobox of easings as I had it: linear, circle, sigmoid, easeOutElastic. 

As other easings will be available the order will change however. As I understand your point is that easings should be sorted by "complexity", right?

**Comment by soreau** [comment]
> As other easings will be available the order will change however. As I understand your point is that easings should be sorted by "complexity", right?

I wanted to use the order listed in wf-config [here](https://github.com/WayfireWM/wf-config/blob/master/src/duration.cpp#L270-L273).

**Comment by NamorNiradnug** [comment]
> I wanted to use the order listed in wf-config [here](https://github.com/WayfireWM/wf-config/blob/master/src/duration.cpp#L270-L273).

Okay, but I think it doesn't really matter for user then? They're sorted in alphabetical order in `std::map` anyway...

**Comment by soreau** [comment]
> > I wanted to use the order listed in wf-config [here](https://github.com/WayfireWM/wf-config/blob/master/src/duration.cpp#L270-L273).
> 
> Okay, but I think it doesn't really matter for user then? They're sorted in alphabetical order in `std::map` anyway...

It matters to me, I would rather retain the ordering.

**Review by soreau — APPROVED** [review]
I tested this and it actually fixed a bug where the easing was defaulting to linear with the reset-to-defaults button. Thank you for addressing the easing ordering in the combobox. You can you merge this when you're ready. 👍

**Comment by NamorNiradnug** [comment]
> I tested this and it actually fixed a bug where the easing was defaulting to linear with the reset-to-defaults button. Thank you for addressing the easing ordering in the combobox. You can you merge this when you're ready. 👍

Thanks! I think it's ready, but I don't have write access to this repo.

**Pull request merged**
